/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package super_puissance_4_chabaud_duchene;

import java.util.Random;

/**
 *
 * @author nykol
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    Joueur ListeJoueurs[] = new Joueur[2];
    Joueur joueurCourant;
    Grille grille = new Grille();

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        panneau_infos_joueurs.setVisible(false);
        panneau_infos_partie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grille.cellule[i][j]);
                panneau_grille.add(cellGraph);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur_2 = new javax.swing.JTextField();
        nom_joueur_1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_infos_joueurs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_j1_nbDesint = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_j1_col = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j2_nbDesint = new javax.swing.JLabel();
        lbl_j2_col = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        panneau_infos_partie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_joueurCourant = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_col_0 = new javax.swing.JButton();
        btn_col_6 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 672, 576));

        panneau_creation_partie.setBackground(new java.awt.Color(255, 255, 204));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2 :");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, 100, 20));

        jLabel2.setText("Nom Joueur 1 :");
        panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 30, 100, 20));
        panneau_creation_partie.add(nom_joueur_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, -1));

        nom_joueur_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur_1ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(nom_joueur_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, -1));

        btn_start.setText("Démarer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 113, 130, 50));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 240, 190));

        panneau_infos_joueurs.setBackground(new java.awt.Color(255, 255, 204));
        panneau_infos_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Joueur 2 :");
        panneau_infos_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setText("Desintegrateur :");
        panneau_infos_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lbl_j1_nbDesint.setText("NbDesintJoueur1");
        panneau_infos_joueurs.add(lbl_j1_nbDesint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel7.setText("Couleur :");
        panneau_infos_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lbl_j1_col.setText("CouleurJoueur1");
        panneau_infos_joueurs.add(lbl_j1_col, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));
        panneau_infos_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 10));

        jLabel9.setText("Couleur :");
        panneau_infos_joueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setText("Desintegrateur :");
        panneau_infos_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lbl_j2_nbDesint.setText("NbDesintJoueur2");
        panneau_infos_joueurs.add(lbl_j2_nbDesint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        lbl_j2_col.setText("CouleurJoueur2");
        panneau_infos_joueurs.add(lbl_j2_col, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        lbl_j2_nom.setText("NomJoueur2");
        panneau_infos_joueurs.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Infos Joueurs");
        panneau_infos_joueurs.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setText("Joueur 1 :");
        panneau_infos_joueurs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lbl_j1_nom.setText("NomJoueur1");
        panneau_infos_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        getContentPane().add(panneau_infos_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 240, 190));

        panneau_infos_partie.setBackground(new java.awt.Color(255, 255, 204));
        panneau_infos_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Infos Jeu");
        panneau_infos_partie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setText("JoueurCourant :");
        panneau_infos_partie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lbl_joueurCourant.setText("NomJoueur");
        panneau_infos_partie.add(lbl_joueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        message.setPreferredSize(new java.awt.Dimension(200, 120));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(150, 80));
        jTextArea1.setRequestFocusEnabled(false);
        message.setViewportView(jTextArea1);

        panneau_infos_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, -1, -1));

        getContentPane().add(panneau_infos_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 240, 190));

        btn_col_0.setText("1");
        btn_col_0.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 96, -1));

        btn_col_6.setText("7");
        btn_col_6.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 30, 96, -1));

        btn_col_5.setText("6");
        btn_col_5.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 96, -1));

        btn_col_4.setText("5");
        btn_col_4.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 30, 96, -1));

        btn_col_3.setText("4");
        btn_col_3.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 30, 96, -1));

        btn_col_2.setText("3");
        btn_col_2.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 30, 96, -1));

        btn_col_1.setText("2");
        btn_col_1.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 30, 96, -1));

        setBounds(0, 0, 1046, 704);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur_1ActionPerformed

    private void btn_col_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_0ActionPerformed
        jouerDansColonne(0);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_0ActionPerformed

    private void btn_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_1ActionPerformed
        jouerDansColonne(1);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_1ActionPerformed

    private void btn_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_3ActionPerformed
        jouerDansColonne(3);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_3ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_infos_joueurs.setVisible(true);
        panneau_infos_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_2ActionPerformed
        jouerDansColonne(2);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_2ActionPerformed

    private void btn_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_4ActionPerformed
        jouerDansColonne(4);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_4ActionPerformed

    private void btn_col_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_5ActionPerformed
        jouerDansColonne(5);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_5ActionPerformed

    private void btn_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_6ActionPerformed
        jouerDansColonne(6);
        joueurSuivant();
    }//GEN-LAST:event_btn_col_6ActionPerformed

    public boolean jouerDansColonne(int indiceColonne) {
        int colonne = indiceColonne;
        int ligne;
        ligne = grille.ajouterJetonDansColonne(joueurCourant.ListeJetons[joueurCourant.nombreJetonsRestant - 1], colonne);
        if (ligne == -1) {
            return false;
        }
        joueurCourant.nombreJetonsRestant--;

        if (grille.cellule[ligne][colonne].presenceTrouNoir()) { // en cas de présence de trou noir supprime le jeton et le trou noir
            grille.supprimerJeton(ligne, colonne);
            grille.cellule[ligne][colonne].activerTrouNoir();
        }
        if (grille.cellule[ligne][colonne].presenceDesintegrateur()) { // en cas de présence de desintégrateur supprime le jeton et le désintégrateur
            grille.cellule[ligne][colonne].recupererDesintegrateur();
            joueurCourant.nombreDesintegrateur++;
        }
        panneau_grille.repaint();
        return true;
    }

    public void joueurSuivant() {
        if (joueurCourant == ListeJoueurs[0]) {
            joueurCourant = ListeJoueurs[1];
        } else {
            joueurCourant = ListeJoueurs[0];
        }
        lbl_joueurCourant.setText(joueurCourant.nom);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    public void initialiserPartie() {
        Random r = new Random();

        String nomJoueur1 = nom_joueur_1.getText(); // Attribution des noms aux joueurs
        ListeJoueurs[0] = new Joueur(nomJoueur1);
        String nomJoueur2 = nom_joueur_2.getText();
        ListeJoueurs[1] = new Joueur(nomJoueur2);

        this.attribuerCouleursAuxJoueurs();

        lbl_j1_nom.setText(nomJoueur1);
        lbl_j2_nom.setText(nomJoueur2);
        lbl_j1_col.setText(ListeJoueurs[0].couleur);
        lbl_j2_col.setText(ListeJoueurs[1].couleur);
        lbl_j1_nbDesint.setText(ListeJoueurs[0].nombreDesintegrateur + "");
        lbl_j2_nbDesint.setText(ListeJoueurs[1].nombreDesintegrateur + "");

        joueurCourant = ListeJoueurs[r.nextInt(2)];
        lbl_joueurCourant.setText(joueurCourant.nom);

        grille.viderGrille();
        for (int i = 0; i < 3; i++) { // placement 3 desintegrateurs
            boolean valide = false;
            while (valide == false) {
                valide = grille.placerDesintegrateur(r.nextInt(6), r.nextInt(7));
            }
        }
        int desintegrateurNoir1 = r.nextInt(5); // création 2 désintegrateurs placés sur des trou noirs
        int desintegrateurNoir2;
        do {
            desintegrateurNoir2 = r.nextInt(5);
        } while (desintegrateurNoir2 == desintegrateurNoir1);
        for (int i = 0; i < 5; i++) { // placement 5 trou noirs
            boolean valide = false;
            while (valide == false) {
                int ligne = r.nextInt(6);
                int colonne = r.nextInt(7);
                valide = grille.placerTrouNoir(ligne, colonne);
                if (valide) {
                    if (i == desintegrateurNoir1 || i == desintegrateurNoir2) { // placement des 2 désintégrateurs associés
                        grille.placerDesintegrateur(ligne, colonne);
                    }
                }
            }
        }
        for (int i = 0; i < 21; i++) {
            ListeJoueurs[0].ajouterJeton(new Jeton(ListeJoueurs[0].couleur));
            ListeJoueurs[1].ajouterJeton(new Jeton(ListeJoueurs[1].couleur));
        }
    }

    public void attribuerCouleursAuxJoueurs() {
        Random r = new Random();

        int num = r.nextInt(2); // nombre aléatoire 0 ou 1
        ListeJoueurs[num].affecterCouleur("rouge");
        ListeJoueurs[(num + 1) % 2].affecterCouleur("jaune"); // (num+1)%2 permet de transformer 1 en 0 / 0 en 1
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_j1_col;
    private javax.swing.JLabel lbl_j1_nbDesint;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_col;
    private javax.swing.JLabel lbl_j2_nbDesint;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_joueurCourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur_1;
    private javax.swing.JTextField nom_joueur_2;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infos_joueurs;
    private javax.swing.JPanel panneau_infos_partie;
    // End of variables declaration//GEN-END:variables
}
